language: node_js
node_js: 'stable'

notifications:
  email: false

before_install:
- echo -e "Host imperial.statustoday.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_3e778d530bf6_key -iv $encrypted_3e778d530bf6_iv
  -in deploy_key.enc -out ~/.ssh/id_rsa -d -d
- chmod 600 ~/.ssh/id_rsa
